import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ data }: any) {
  const comments = data.slice(0, 10);
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <button
          className="mt-5 bg-green-700 text-white ml-5 rounded-md p-2 text-3xl font-bold"
          onClick={() => router.push("/users")}
        >
          users
        </button>
        <ul>
          {comments.map(
            (comment: { id: number; body: string; postId: number }) => (
              <>
                <span>{comment.postId}:</span>
                <li key={comment.id}>{comment.body}</li>
              </>
            )
          )}
        </ul>
      </main>
    </>
  );
}
export async function getStaticProps() {
  const res = await fetch("https://jsonplaceholder.typicode.com/comments");
  const data = await res.json();

  return {
    props: { data },
  };
}
