import Head from "next/head";

import Button from "@/components/Button";
import IComment from "@/interfaces/IComment";
import { GetStaticProps } from "next";

export default function Home({ data }: { data: IComment[] }) {
  const comments = data.slice(0, 10);
  const Menu = () => {
    return (
      <>
        <Button route="/users">Users</Button>
        <Button route="/albums">Albums</Button>
        <Button route="/pics">Pics</Button>
        <Button route="/todos">Todos</Button>
      </>
    );
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Menu />
        <ul>
          {comments.map((comment) => (
            <>
              <span>{comment.postId}:</span>
              <li key={comment.id}>{comment.body}</li>
            </>
          ))}
        </ul>
      </main>
    </>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const res = await fetch("https://jsonplaceholder.typicode.com/comments");
  const data = await res.json();
  return {
    props: { data },
  };
};
